//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectofinalweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class socios
    {
        public int sociosId { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string cedula { get; set; }
        public string Foto { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string sexo { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string afiliados { get; set; }
        public string membresia { get; set; }
        public string lugar_trabajo { get; set; }
        public string direccion_oficina { get; set; }
        public string tel_oficina { get; set; }
        public Nullable<bool> Estado_miembresia { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
    }
}
